GET http://localhost:5210/songs/

###
GET http://localhost:5210/songs/5

###
DELETE http://localhost:5210/songs/5

###
POST http://localhost:5210/songs/
Content-Type: application/json

{
    "Title": "34+35", 
    "Album":"Positions", 
    "Artist":"Ariana Grande",
    "Genre":"Blues", 
    "ReleaseDate":"2006-05-06"
}

###
PUT http://localhost:5210/songs/5
Content-Type: application/json

{
    "Title": "Position", 
    "Album":"Positions", 
    "Artist":"Ariana Grande",
    "Genre":"Blues", 
    "ReleaseDate":"2006-05-06"
}